"""Set of functions and classes used to handle data with Open, High, Low, Close and Volume"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/01_ohlcv.ipynb.

# %% auto #0
__all__ = ['candlestick_plot', 'resample_ohlcv', 'autocorrelation_ohlcv']

# %% ../nbs-dev/01_ohlcv.ipynb #6adcdcd9
from datetime import datetime
from pathlib import Path
from typing import Optional

import pandas as pd
from bokeh.plotting import figure, output_notebook, show

# %% ../nbs-dev/01_ohlcv.ipynb #742ad8e3
def candlestick_plot(
    df:pd.DataFrame,        # df with datetime index, and at least following columns 'Open', 'High', 'Low', 'Close', 'Volume'
    width:int = 950,        # height of the plot figure
    height:int = 600,       # height of the plot figure
    chart_title:str = '-',   # title of the chart
    fig:figure|None = None  # figure to allow superposition of other lines on candlestick plot
    )-> None:      
    """Create a candlestick chart (Bokeh) using a dataframe with 'Open', 'High', 'Low', 'Close', 'Volume'."""

    if fig is None:
        p = figure(width=width, height=height, title=chart_title, x_axis_type="datetime")
    else:
        p = fig
    p.xaxis.major_label_orientation = 3.1415 / 4
    p.grid.grid_line_alpha = 0.5

    # x_axis_type as 'datetime' means that the width dimensions are measured in milliseconds
    # note: sometimes, the two first bars are not contiguous (e.g. bar[0]=Fri and bar[1]=Mon)
    # in such case, if interval(bar[1],bar[0]) > interval(contiguous bars).
    # instead of taking the first interval, we take the min interval across the full index
    intervals = df.index.unique().to_series() - df.index.unique().to_series().shift(1)
    interval_in_ms = intervals[1:-1].min().total_seconds() * 1000
    ratio = 0.60

    inc = df['Close'] > df['Open']
    dec = df['Close'] < df['Open']
    flat = df['Close'] == df['Open']

    p.segment(df[inc].index, df.loc[inc, 'High'], df[inc].index, df.loc[inc, 'Low'], color='darkgreen')
    p.segment(df[dec].index, df.loc[dec, 'High'], df[dec].index, df.loc[dec, 'Low'], color='darkred')
    p.segment(df[flat].index, df.loc[flat, 'High'], df[flat].index, df.loc[flat, 'Low'], color='black')

    p.vbar(x=df[inc].index,
           bottom=df.loc[inc, 'Open'],
           top=df.loc[inc, 'Close'],
           width=ratio * interval_in_ms,
           fill_color="darkgreen",
           line_color="darkgreen")
    p.vbar(x=df[dec].index,
           bottom=df.loc[dec, 'Close'],
           top=df.loc[dec, 'Open'],
           width=ratio * interval_in_ms,
           fill_color="darkred",
           line_color="darkred")
    p.vbar(x=df[flat].index,
           bottom=df.loc[flat, 'Close'],
           top=df.loc[flat, 'Open'],
           width=ratio * interval_in_ms,
           fill_color="black",
           line_color="black")

    if fig is None:
        show(p)

# %% ../nbs-dev/01_ohlcv.ipynb #8bf00598
def resample_ohlcv(
    df:pd.DataFrame,    # `df` with datetime index, and at least following columns 'Open', 'High', 'Low', 'Close'. Optional 'Volume' 
    rule_str='W-FRI'    # `DateOffset` alias for resampling. Default: 'W-FRI'. Other commons: 'D', 'B', 'W', 'M'
    ) -> pd.DataFrame:  # resampled `df` with columns 'Open', 'High', 'Low', 'Close'. Optional 'Volume'
    """
    Resample a `DataFrame` with OHLCV format according to given rule string.

    The re-sampling is applied to each of the OHLC and optional V column. Re-sampling aggregate applies `first()`, `max()`, `min()`, `last()` and `sum()` to OHLCV respectively.
    """

    resampled_df = df.resample(rule_str)
    resampled_index = resampled_df.groups
    # resample() returns a Re-sampler object, on which a function must be applied, e.g. first(), max(), aggregate()

    ohlcv_df = pd.DataFrame(
        {'Open': resampled_df['Open'].first(),
         'High': resampled_df['High'].max(),
         'Low': resampled_df['Low'].min(),
         'Close': resampled_df['Close'].last(),
        },
        index=resampled_index
        )

    if 'Volume' in resampled_df.count().columns:
        ohlcv_df['Volume'] = resampled_df['Volume'].sum()

    ohlcv_df.index.name = rule_str

    return ohlcv_df

# %% ../nbs-dev/01_ohlcv.ipynb #556ecd31
def autocorrelation_ohlcv(
    df:pd.DataFrame,       # `df` with `DateTimeIndex`, with Open, High, Low, Close
    max_lag: int = 10,     # Maximum lag to consider for the autocorrelation
    ohlc_col:str='Close',  # Columns to use for the autocorrelation. Default: 'Close'. Options: 'Open', 'High', 'Low', 'Close'
    ) -> pd.Series:
    """
    Return     autocorrelation for a range of lags and for the selected ohlc_col_col defined.
    """
    lag_range = range(1, max_lag+1)
    autocorr_values = [df[ohlc_col].autocorr(lag) for lag in lag_range]
    series_autocorrelation = pd.Series(autocorr_values, index=lag_range, name='Autocorrelation')

    return series_autocorrelation
