"""Predifined sklearn pipeline to process and create features with financial data"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs-dev/02_pipelines.ipynb.

# %% auto 0
__all__ = ['MyBaseTransformer', 'ReturnTransformer', 'StdTransformer', 'MATransformer', 'EMATransformer', 'simplify_colnames',
           'dframe', 'build_pipeline']

# %% ../nbs-dev/02_pipelines.ipynb 4
import re

import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, TransformerMixin, BaseEstimator
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# %% ../nbs-dev/02_pipelines.ipynb 7
class MyBaseTransformer(BaseEstimator, TransformerMixin):
    """Base class for my custom transformers"""
    def __init__(self):
        self.input_features_ = None
        self.output_features_ = None
        self.postfix = "transformed"

    def fit(self, X, y=None):
        if hasattr(X, 'columns'):
            self.input_features_ = X.columns.tolist()
        else:
            self.input_features_ = [f'f_{i}' for i in range(X.shape[1])]
        self.output_features_ = [f"{feat}_{self.postfix}" for feat in self.input_features_]
        return self

    def transform(self, X) -> np.ndarray:
        X = X.copy()
        return X.values

    def get_feature_names_out(self, input_features=None) -> list[str]|None:
        if input_features is not None:
            return [f"{feat}_{self.postfix}" for feat in input_features]
        else:
            return self.output_features_

# %% ../nbs-dev/02_pipelines.ipynb 10
class ReturnTransformer(MyBaseTransformer):
    """Evaluate the percentage return over 1 or more periods"""
    def __init__(self, periods:int=1) -> None:
        super().__init__()
        self.periods = periods
        self.postfix = f"ret{self.periods}"
        self.nickname = f"return{self.periods}"

    def transform(self, X) -> np.ndarray:
        """percentage change with previous bar, fist bar is 0"""
        X = X.copy()
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X)
        return X.pct_change(periods=self.periods).fillna(0.0).values

# %% ../nbs-dev/02_pipelines.ipynb 12
class StdTransformer(MyBaseTransformer):
    """Evaluate the standard deviation over a window"""
    def __init__(self, window:int=5) -> None:
        super().__init__()
        self.window = window
        self.postfix = f"std{self.window}"
        self.nickname = f"std{self.window}"

    def transform(self, X) -> np.ndarray:
        X = X.copy()
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X)
        return X.rolling(window=self.window, min_periods=1).std().values

# %% ../nbs-dev/02_pipelines.ipynb 14
class MATransformer(MyBaseTransformer):
    """Evaluate the moving average over a window"""
    def __init__(self, window:int=5) -> None:
        super().__init__()
        self.window = window
        self.postfix = f"MA{self.window}"
        self.nickname = f"ma{self.window}"

    def transform(self, X) -> np.ndarray:
        X = X.copy()
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X)
        return X.rolling(window=self.window, min_periods=1).mean().values

# %% ../nbs-dev/02_pipelines.ipynb 15
class EMATransformer(MyBaseTransformer):
    """Evaluate the exponential moving average over a window"""
    def __init__(self, window:int=5) -> None:
        super().__init__()
        self.window = window
        self.postfix = f"EMA{self.window}"
        self.nickname = f"ema{self.window}"

    def transform(self, X) -> np.ndarray:
        X = X.copy()
        if not isinstance(X, pd.DataFrame):
            X = pd.DataFrame(X)
        return X.ewm(span=self.window).mean().values

# %% ../nbs-dev/02_pipelines.ipynb 18
def simplify_colnames(cols)->list[str]:
    """Simplify the columns names by removing the prefix"""
    pat = re.compile(r"[\w\d\-]*_{2}(?P<end>\w*)")
    cols = [pat.match(c).group('end') for c in cols]
    return cols

# %% ../nbs-dev/02_pipelines.ipynb 22
def dframe(
    df:pd.DataFrame,    # dataframe to transform 
    pipe:BaseEstimator,      # pipeline to apply on the dataframe
    fit:bool=True       # fit_transform if True, transform if False
    ) -> pd.DataFrame:  # formated DataFrame
    """Takes a pipeline, (optionaly) fit it on df and transform it, then return a well formated DataFrame"""
    if fit:
        data = pipe.fit_transform(df)
    elif not fit:
        data = pipe.transform(df)
    else:
        raise ValueError("fit must be a boolean")

    df_proc = pd.DataFrame(
        data=data, 
        columns=simplify_colnames(pipe.get_feature_names_out()),
        index=df.index)
    return df_proc

# %% ../nbs-dev/02_pipelines.ipynb 27
def build_pipeline(
    coi:list[str],                  # list of columns to use for feature engineering 
    transforms:list[BaseEstimator], # list of feature engineering transformers to apply to each column in coi
    stats: list[BaseEstimator]      # list of stats transformers to apply to engineered feature
    ) -> BaseEstimator :
    """Build a pipeline using cols in `coi`, transformers in `transforms` and stats in `stats`

    The output will be a pipeline that takes a OHLCV DataFrame and returns:

     - the original OHLCV columns
     - for the columns in `coi`, engineers features by applying each of the pipelines in `transforms`
     - then adds the statistics in `stats` to each of the engineered features
    """
    feature_stats_steps = [('thru', 'passthrough')]
    for stat in stats:
        feature_stats_steps.append((stat.nickname, stat))   #type:ignore
    feature_stats = FeatureUnion(feature_stats_steps)       #type:ignore
    feature_stats.nickname = 'stats'                        #type:ignore
    
    feature_engineering = [Pipeline(
        [(t.nickname, t),(t.nickname+feature_stats.nickname, feature_stats)] #type:ignore
        ) for t in transforms]
    pipe_steps = [('thru', 'passthrough', ['Open', 'High', 'Low', 'Close', 'Volume'])]

    for feat in feature_engineering:
        pipe_steps.append((feat.steps[0][0], feat, coi))

    pipe = ColumnTransformer(pipe_steps)

    return pipe
